# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Runs every 6 hours and also manually from the Actions tab
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with full history
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Generate the snake animation
      - uses: Platane/snk@master
        with:
          github_user_name: maxctrdev
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy the generated files to the 'output' branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
